### ISSUE TITLE
Add the unit tests action status to the read me 

### ISSUE THREAD

**Issue by anjula-sack** [tillioss/tilli-ide#40]
**Is your feature request related to a problem? Please describe.**
* We need to show the unit test status in the readme so we can view it easily

**Describe the solution you'd like**
* Go to the readme file
* Add the following code to the readme
* Create a pull request

`[![Unit tests](https://github.com/tillioss/tilli-ide/actions/workflows/unit.yml/badge.svg)](https://github.com/tillioss/tilli-ide/actions/workflows/unit.yml)`

**Comment by Sanjana0319** [comment]
I would like to work on this.
